apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wp-deploy
  labels:
    env: wp-pod
spec:
  selector:
    matchLabels:
      env: wp-pod1
  replicas: 1
  template:
    metadata:
      labels:
        env: wp-pod1
    spec:
      containers:
        - name: wp-cont
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER                 
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    env: db-cont
spec:
  selector:
    matchLabels:
      test: db-test
  replicas: 1
  template:
    metadata:
      labels:
        test: db-test
    spec:
      containers:
        - name: db-pod
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: random
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER                 
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME             

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deploy
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer-cont
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer-cont
    spec:
      containers:
        - name: adminer-container
          image: adminer

    
  

        

        
    