apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: igress-rules
spec:
  rules:
    - host: knz.com
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleetman-webapp 
                port:
                  number: 80
          - path: /fila
            pathType: Exact
            backend:
              service:
                name: fleetman-queue
                port:
                  number: 8161
    