apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: igress-rules
  annotations:
    nginx.ingress.kubernets.io/auth-type: basic
    nginx.ingress.kubernets.io/auth-secret: mycredentials
    nginx.ingress.kubernets.io/auth-realm: "Password"
spec:
  rules:
    - host: knz.com
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleetman-webapp 
                port:
                  number: 80
    - host: queue.knz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleetman-queue
                port:
                  number: 8161
    
