apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: web-app
    release: r0
spec:
  containers:
    - name: web-app-container
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0

--- 
apiVersion: v1
kind: Pod
metadata:
  name: web-app-1
  labels:
    app: web-app
    release: r0-5
spec:
  containers:
    - name: web-app-container
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5