apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    env: test
spec:
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      name: nginx-pod
      labels:
        env: test
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.25.4
  replicas: 3