apiVersion: v1
kind: Service
metadata: 
  name: frontend-tmp-svc
spec:
  selector:
    env : test 
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30003
  type: NodePort
