apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: wp-db
spec:
  containers:
    - name: mysql-container
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: RootPass
        - name: MYSQL_USER
          value: wp-user
        - name: MYSQL_PASSWORD
          value: WpPassword
        - name: MYSQL_DATABASE
          value: wp-db
