apiVersion: v1 
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote-ns
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 31001
      name: "result-service"
  selector:
    app: result
