apiVersion: v1 
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote-ns
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 31000
      name: "vote-service"
  selector:
    app: vote
