apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote-ns
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
              name: result
  replicas: 1

      
    