apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote-ns
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: vote
  replicas: 1

      
    