#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote-ns
#Spec do deployment
spec:
  #Runtime ok v2 antes de substituir pod v1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    #spec do container
    spec:
      containers:
        - name: vote-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: vote
  #Número de réplicas desse deploy
  replicas: 1


      
    